In [2]:
dist1 = {136:"Rishabh kumar",100:"Aniket Lad",103:"Soumen Mondal"}
print(dist1)
print(dist1.keys())
print(dist1.values())


{136: 'Rishabh kumar', 100: 'Aniket Lad', 103: 'Soumen Mondal'}
dict_keys([136, 100, 103])
dict_values(['Rishabh kumar', 'Aniket Lad', 'Soumen Mondal'])


In [3]:
dist1.update({69:"Mriganka Adhikary"})

In [4]:
print(dist1)


{136: 'Rishabh kumar', 100: 'Aniket Lad', 103: 'Soumen Mondal', 69: 'Mriganka Adhikary'}


In [5]:
import numpy as np
x=np.array([2,3,4,5])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[2 3 4 5]


In [6]:
x=np.array([2,3,'n',5])
print(x)


['2' '3' 'n' '5']


In [7]:
d=np.arange(start=1,stop=100,step=5)
print(d)


[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [8]:

np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.random.rand(6)

array([0.16797756, 0.8851407 , 0.06873169, 0.7279946 , 0.17300213,
       0.38493083])

In [10]:
np.logspace(start=1,stop=100,num=5,endpoint=True,base=10.0)

array([1.00000000e+001, 5.62341325e+025, 3.16227766e+050, 1.77827941e+075,
       1.00000000e+100])

In [17]:
grid=np.arange(start=1,stop=10).reshape(3,3)

In [18]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
grid=np.arange(start=1,stop=10)
print(grid)

[1 2 3 4 5 6 7 8 9]


In [22]:
grid=np.arange(start=1,stop=10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.arange(start=1,stop=10).reshape(3,3)
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(a+b)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [26]:
print(a*b)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [28]:
print(a)
a[0,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [29]:
a_sub=a[:2,:2]

In [30]:
print(a_sub)

[[1 2]
 [4 5]]


In [31]:
a_sub[0, 1] = 10

In [32]:
print(a_sub)

[[ 1 10]
 [ 4  5]]


In [38]:
a_sub = np.append(a, [[10], [11],[14]], axis=1)
print(a_sub)

[[ 1 10  3 10]
 [ 4  5  6 11]
 [ 7  8  9 14]]
